import type { Metadata } from "next";
import { Providers } from './providers';
import NavMenu from "./menu/nav-menu";
import "./styles/_fonts.scss";
import "./globals.scss";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Providers>
          <NavMenu />
          <main>
            {children}
          </main>
        </Providers>
      </body>
    </html>
  );
}
