import type { Metadata } from "next";
import { Providers } from './providers';
import NavMenu from "./menu/nav-menu";
import "./globals.scss";

export const metadata: Metadata = {
  title: "Atelier IT App",
  description: "Generated by 3x3c_t3c1337",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Providers>
          <NavMenu />
          <main>
            {children}
          </main>
        </Providers>
      </body>
    </html>
  );
}
